FROM golang:1.20

ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

RUN mkdir -p /go/src/github.com/Blackmocca/hopp-api-doc
WORKDIR /go/src/github.com/Blackmocca/hopp-api-doc

# Move to project folder
WORKDIR /go/src/github.com/Blackmocca/hopp-api-doc

COPY . . 
RUN go mod tidy     

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o   /go/src/github.com/Blackmocca/hopp-api-doc/tmp/app main.go

FROM alpine:latest 
RUN apk --no-cache add ca-certificates
WORKDIR /usr/app

ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

COPY --from=0 /go/src/github.com/Blackmocca/hopp-api-doc/tmp/app .
RUN mkdir -p ./assets
RUN mkdir -p ./docs
COPY --from=0 /go/src/github.com/Blackmocca/hopp-api-doc/public public
COPY --from=0 /go/src/github.com/Blackmocca/hopp-api-doc/hopp-cli hopp-cli

EXPOSE 3000

CMD ["./app"]  

