FROM golang:1.20

ARG app_name
ARG build_number
ARG version
ENV env_build_number=${build_number}
ENV env_version=${version}
ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

RUN mkdir -p /go/src/github.com/Blackmocca/hopp-api-doc
WORKDIR /go/src/github.com/Blackmocca/hopp-api-doc

# Move to project folder
WORKDIR /go/src/github.com/Blackmocca/hopp-api-doc

COPY . . 
RUN go mod tidy     
RUN go install github.com/githubnemo/CompileDaemon@v1.4.0

RUN  go build -o  /go/src/github.com/Blackmocca/hopp-api-doc/tmp/app main.go

EXPOSE 3000

ENTRYPOINT CompileDaemon -include=go.mod -log-prefix=false -color=true -build="go build -o ./tmp/app main.go" -command="./tmp/app" 
